version: '3.7'

services:
  ctfd-REPLACED_NAME:
    build: .
    user: root
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@db-REPLACED_NAME/ctfd
      - REDIS_URL=redis://cache-REPLACED_NAME:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - USE_SSL=false
      - REVERSE_PROXY=true
      - USE_RELOAD=false
    volumes:
      - REPLACED_FULL_PATH/CTFd/.data/CTFd/REPLACED_NAME/logs:/var/log/CTFd
      - REPLACED_FULL_PATH/CTFd/.data/CTFd/REPLACED_NAME/uploads:/var/uploads
      - REPLACED_FULL_PATH/CTFd:/opt/CTFd:ro
    depends_on:
      - db-REPLACED_NAME
    networks:
      default:
      internal:
    expose:
      - '8000'

  db-REPLACED_NAME:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - REPLACED_FULL_PATH/CTFd/.data/mysql/REPLACED_NAME:/var/lib/mysql
    networks:
      internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache-REPLACED_NAME:
    image: redis:4
    restart: always
    volumes:
      - REPLACED_FULL_PATH/CTFd/.data/redis/REPLACED_NAME:/data
    networks:
      internal:

networks:
  default:
    name: ctf_default
  internal:
    name: ctf_internal
    internal: true
